sudo: required
language: node_js
install:
  - npm install -g codecov babel-cli jasmine
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5.0.0

before_script:
  - npm prune
script:
  - npm run test:upload-coverage
  - codecov
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
